### ISSUE TITLE
Weird 404 Error occurs after some time reading.

### ISSUE THREAD

**Issue by zyansheep** [blainehansen/hopeful-pathway#1]
While I'm writing a more detailed comment-issue, I thought I'd put this in a separate issue to avoid clutter.

![Screenshot_20220511_192257](https://user-images.githubusercontent.com/20029431/167963279-02b9b53e-455c-44ec-a70b-30dc2c2e26f3.png)

This is kinda hard to reproduce, but seems to happen after some time of reading while clicking the links at the bottom.

Edit: Found another error:
![screenshot](https://user-images.githubusercontent.com/20029431/167969582-e3ba464c-b20b-43f4-b5e9-934a9466f192.png)

**Comment by blainehansen** [comment]
It looks like this was happening roughly at the same time I was pushing stuff to the repo, so this might have simply been a side effect of the build process replacing files. If you can find a way to reproduce it I'll be happy to investigate :)
