### ISSUE TITLE
https://persistentdemocracy.org is down

### ISSUE THREAD

**Issue by charlielidbury** [blainehansen/hopeful-pathway#3]
I'm sure you know already, but thought I'd pop it here in case you didn't.

**Comment by blainehansen** [comment]
Seems fine to me? Can you give me more information? All of my dashboards look good.

![Screenshot from 2023-01-27 14-34-09](https://user-images.githubusercontent.com/5805971/215204916-35542ddf-6057-46a0-9ec0-1cbae4e8e891.png)

**Comment by charlielidbury** [comment]
The connection just times out for me. I'm in London, United Kingdom. Where abouts is it hosted?

Btw, I ended up reading a lot of what you've written via the way back machine + the markdown files in the github - couldn't agree more with what you're saying. Would love to connect over some instant messaging thing.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26258764/215269964-f50ed15c-34ba-47eb-b66f-2a7b132ac0f5.png">

**Comment by blainehansen** [comment]
I'm not sure what to do about this :/ I tried a few sites that checked a url from different geo proxies, and they all said it was fine :shrug: It's hosted on netlify, which is fairly mainstream right?

Feel free to add me on discord: `blainehansen#5661`

**Comment by charlielidbury** [comment]
Thanks, have sent you an invite
